services:
  vosk_asr:
    container_name: vosk_asr
    build: ./vosk_asr
    ports:
      - "2700:2700"
    volumes:
      - ./vosk_asr/models:/app/models
      - ./pip_cache:/root/.cache/pip

  gemini_server:
    build: ./gemini
    container_name: gemini_server
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    ports:
      - "8765:8765"
    tty: true
    volumes:
      - ./pip_cache:/root/.cache/pip  # mount host folder for persistent pip cache

  # gemini_client:
  #   build: ./websockets
  #   container_name: gemini_client
  #   depends_on:
  #     - gemini_server
  #   stdin_open: true
  #   tty: true
  #   command: python ws_client.py
  #   volumes:
  #     - ./pip_cache:/root/.cache/pip

  node-website:
    build: ./website
    container_name: node_website
    ports:
      - "3000:3000"  # Expose port 3000 to access the app
    volumes:
      - ./website:/app  # Mount the current directory to /app in the container (useful for development)
    devices:
      - "/dev/snd:/dev/snd"  # Allow Docker container to access the host's sound devices
    # environment:
    #   - NODE_ENV=production
    restart: always
